### PR TITLE
Add optimisation compiler flags

### PR DESCRIPTION
**Pull request by duncanmmacleod**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@lpsinger, can you confirm this is what you wanted?

**Comment by lpsinger** [comment]
No. I looked at the Azure build logs, and somehow the last optimization flag is still `-O2`.

**Comment by duncanmmacleod** [comment]
Ok, I patched `CPPFLAGS` as well, which I think has done the trick, can you check again?

**Comment by lpsinger** [comment]
That did the trick. The compiler invocation is now:

`/home/conda/feedstock_root/build_artifacts/ligo.skymap_1591044182435/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/ligo.skymap_1591044182435/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/ligo.skymap_1591044182435/work=/usr/local/src/conda/ligo.skymap-0.3.1 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/ligo.skymap_1591044182435/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold=/usr/local/src/conda-prefix -O3 -flto -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/conda/feedstock_root/build_artifacts/ligo.skymap_1591044182435/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include -O3 -fPIC -I/home/conda/feedstock_root/build_artifacts/ligo.skymap_1591044182435/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include -I/home/conda/feedstock_root/build_artifacts/ligo.skymap_1591044182435/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.8/site-packages/numpy/core/include -I/home/conda/feedstock_root/build_artifacts/ligo.skymap_1591044182435/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include/python3.8 -c src/bayestar_sky_map.c -o build/temp.linux-x86_64-3.8/src/bayestar_sky_map.o -std=gnu11 -DGSL_RANGE_CHECK_OFF -DHAVE_INLINE -fopenmp`

**Pull request merged**
