### PR TITLE
Update to 2.0.0

### PR DESCRIPTION
**Pull request by lpsinger**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by lpsinger** [comment]
@conda-forge-admin, please rerender

**Comment by lpsinger** [comment]
@conda-forge-admin, please rerender

**Comment by lpsinger** [comment]
@conda-forge-admin, please rerender

**Comment by lpsinger** [comment]
@duncanmmacleod, how do I tell Conda that I want to build using numpy 2.0.0rc1? The build is failing with this error message:

```
nothing provides requested numpy >=2.0.0rc1
```

However, I can see from https://anaconda.org/conda-forge/numpy/files that there are Conda packages for this version of Numpy.

**Comment by duncanmmacleod** [comment]
> @duncanmmacleod, how do I tell Conda that I want to build using numpy 2.0.0rc1? The build is failing with this error message:
> 
> ```
> nothing provides requested numpy >=2.0.0rc1
> ```
> 
> However, I can see from https://anaconda.org/conda-forge/numpy/files that there are Conda packages for this version of Numpy.

I think the problem is that they are on a different label (`numpy_dev`) so conda can't see them by default?

You are best to do all of this hacking around the conda-forge defaults in a dedicated `recipe/conda_build_config.yaml` file. That is used as an input to `conda smithy` on top of the `conda_build_config.yaml` provided by the `conda-forge-pinning` package, to generate the `.ci_support/*.yaml` files for each build. Here's what works for me:

```yaml
channel_sources:
  - conda-forge/label/numpy_dev,conda-forge
numpy:
  - '2.0.0rc1'
  - '2.0.0rc1'
  - '2.0.0rc1'
python:
  - '3.9'
  - '3.10'
  - '3.11'
python_impl:
  - cpython
  - cpython
  - cpython
```

Only the `channel_sources` override is actually needed to have conda-build see the numpy RC, however the other lines enable you to undo all of your hacks to the `meta.yaml` file and override the numpy version in a less disruptive way. Then regenerate the feedstock with conda-smithy.

**Comment by lpsinger** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
